runtime: python27
threadsafe: true
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: this field is required, but ignored

runtime_config:
  python_version: 2
  
env_variables:
    CLOUDSQL_CONNECTION_NAME: 35.192.165.227
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: root

libraries:
- name: MySQLdb
  version: "latest"

 